$engine: 3
$minFxVersion: 13005
$onesync: on
name: nage
version: 1.0.0
author: Nage Team
description: The official recipe for Nage Core.

tasks:
  ## Prepare recipe
  - action: download_github
    src: https://github.com/NageTeam/txAdminRecipe
    ref: main
    dest: ./tmp/nage

  - action: move_path
    src: ./tmp/nage/server.cfg
    dest: ./server.cfg

  - action: move_path
    src: ./tmp/nage/nagelogo.png
    dest: ./nagelogo.png

  - action: connect_database

  ## Default CFX resources
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: master
    subpath: resources
    dest: ./resources/[cfx]

  ## oxmysql
  - action: download_file
    url: https://github.com/overextended/oxmysql/releases/latest/download/oxmysql.zip
    path: ./tmp/oxmysql.zip
  - action: unzip
    src: ./tmp/oxmysql.zip
    dest: ./resources/[other]

  ## nagecore
  - action: download_file
    url: https://github.com/NageTeam/nage_core/releases/download/nage_core/nage.zip
    path: ./tmp/nage.zip
  - action: unzip
    src: ./tmp/nage.zip
    dest: ./resources/[core]

  - action: replace_string
    file: ./resources/[core]/nage/nage.sql
    search: "nage"
    replace: "{{dbName}}"

  - action: replace_string
    mode: all_vars
    file:
      - ./resources/[core]/nage/nage.sql

  - action: query_database
    file: ./resources/[core]/nage/nage.sql

  ## Nage Loadingscreen
  - action: download_github
    src: https://github.com/NageTeam/nage_loadingscreen/releases/download/nage_loadingscreen/nage_loadingscreen.zip
    ref: nage
    dest: ./resources/[core]/nage_loadingscreen

  ## Nage Hud
  - action: download_github
    src: https://github.com/NageTeam/nage_hud/releases/download/nage_hud/nage_hud.zip
    ref: nage
    dest: ./resources/[core]/nage_hud

  ## Nage Scoreboard
  - action: download_github
    src: https://github.com/NageTeam/nage_scoreboard/releases/download/nage_scoreboard/nage_scoreboard.zip
    ref: nage
    dest: ./resources/[core]/nage_scoreboard

  ## pma-voice
  - action: download_github
    src: https://github.com/AvarianKnight/pma-voice
    ref: main
    dest: ./resources/[other]/pma-voice

  ## bob74_ipl
  - action: download_github
    src: https://github.com/Bob74/bob74_ipl
    ref: master
    dest: ./resources/[other]/bob74_ipl

  ## Clear Temp
  - action: remove_path
    path: ./tmp
